disabled_rules:
  - opening_brace
  - trailing_comma

line_length:
  warning: 120
  error: 200
  ignores_multiline_strings: true

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 3

type_name:
  excluded:
    - ID
